#!/usr/bin/env bash
#
# gen_certs.sh <laptop-ip>
#
# Generates, on your laptop:
#   certs/ca.key, certs/ca.crt          - your own throwaway test CA (RSA 2048)
#   certs/server.key, certs/server.crt  - mosquitto's server cert, signed by
#                                          that CA, with <laptop-ip> as a SAN
#
# ...and, back in the STM32 project:
#   Core/Inc/ca_cert.h                  - ca.crt converted to a DER byte array,
#                                          so the firmware can verify the
#                                          broker's cert without a filesystem
#
# Run this again (it overwrites everything) if your laptop's IP changes.
#
# Requires: openssl.

set -euo pipefail

if [ $# -ne 1 ]; then
    echo "usage: $0 <laptop-ip>   (the IP the STM32 board will connect to)"
    exit 1
fi
LAPTOP_IP="$1"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CERT_DIR="$SCRIPT_DIR/certs"
FW_INC_DIR="$SCRIPT_DIR/../Core/Inc"

mkdir -p "$CERT_DIR"
cd "$CERT_DIR"

echo "==> 1. Throwaway test CA (RSA 2048, 10 years - this is a bench-test CA,"
echo "        not something to reuse for anything real)"
openssl genrsa -out ca.key 2048 2>/dev/null
openssl req -x509 -new -nodes -key ca.key -sha256 -days 3650 \
    -subj "/CN=STM32-MQTT-Test-CA" -out ca.crt

echo "==> 2. Broker server key + CSR (RSA 2048), CN/SAN = ${LAPTOP_IP}"
openssl genrsa -out server.key 2048 2>/dev/null
openssl req -new -key server.key \
    -subj "/CN=${LAPTOP_IP}" -out server.csr

cat > server.ext << EOF
subjectAltName = IP:${LAPTOP_IP}
extendedKeyUsage = serverAuth
EOF

echo "==> 3. Sign the server cert with our test CA"
openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial \
    -days 825 -sha256 -extfile server.ext -out server.crt

rm -f server.csr server.ext ca.srl

echo "==> 4. Embedding ca.crt as a C byte array for the firmware"
mkdir -p "$FW_INC_DIR"
CA_DER="$CERT_DIR/ca.der"
openssl x509 -in ca.crt -outform der -out "$CA_DER"

{
    echo "/*"
    echo " * ca_cert.h - AUTO-GENERATED by tools/gen_certs.sh, do not hand-edit."
    echo " *"
    echo " * DER (ASN.1) encoding of certs/ca.crt, the throwaway test CA that"
    echo " * signed the mosquitto broker's certs/server.crt for IP ${LAPTOP_IP}."
    echo " * Loaded at startup by MQTT_TLS_NewContext() via"
    echo " * wolfSSL_CTX_load_verify_buffer(..., WOLFSSL_FILETYPE_ASN1)."
    echo " *"
    echo " * Regenerate by re-running: tools/gen_certs.sh <laptop-ip>"
    echo " */"
    echo
    echo "#ifndef __CA_CERT_H"
    echo "#define __CA_CERT_H"
    echo
    echo "#include <stdint.h>"
    echo
    echo "static const uint8_t g_ca_cert_der[] = {"
    od -An -tx1 -v "$CA_DER" | awk '{
        line=""
        for (i=1; i<=NF; i++) line = line "0x" $i ", "
        print "    " line
    }'
    echo "};"
    echo
    echo "static const uint32_t g_ca_cert_der_len = sizeof(g_ca_cert_der);"
    echo
    echo "#endif /* __CA_CERT_H */"
} > "$FW_INC_DIR/ca_cert.h"

echo
echo "Done."
echo "  Broker files : $CERT_DIR/{ca.crt,ca.key,server.crt,server.key}"
echo "  Firmware file: $FW_INC_DIR/ca_cert.h  (rebuild the STM32 project after this)"
echo
echo "Point mosquitto (tools/mosquitto_test.conf) at:"
echo "  cafile   $CERT_DIR/ca.crt"
echo "  certfile $CERT_DIR/server.crt"
echo "  keyfile  $CERT_DIR/server.key"
